# This is a GitHub workflow which will be triggered on a tag event and will create a release on GitHub.
# It will also upload the built files as release assets.
# The workflow will only be triggered if the tag's name is a valid semver string.

name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Create release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create release
        run: |
          gh release create ${{ github.ref }} \
            --verify-tag
            --generate-notes \
            --latest \
            --draft \
            --prerelease
