name: Dependabot Auto-Merge for NPM

on:
  pull_request:
    branches:
      - trunk
    paths:
      - "package-lock.json"
      - ".github/workflows/dependabot-npm.yml"

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: "dependabot-npm-${{ github.event_name }}-${{ github.event.pull_request.number }}"
  cancel-in-progress: true

jobs:
  audit:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache-dependency-path: "package-lock.json"
          cache: npm

      - name: Audit
        run: npm audit --audit-level=high

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm run test --if-present

  merge:
    needs: audit
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Enable auto-merge for Dependabot PRs
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch'
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
